package boundaryCliente;

import java.awt.Cursor;
import java.sql.Date;
import java.time.LocalDate;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import boundary.BoundaryCliente;
import entity.Dipinto;
import entity.LineaProdotto;
import entity.Prodotto;
 

/**
 *
 * @author flavi
 */
public class Carrello extends javax.swing.JFrame {

    /**
     * Creates new form Carrello
     */ 
	
	private BoundaryCliente boundaryCliente = BoundaryCliente.getIstance();
	private String codiceProdottoSelezionato;
	
	
    public Carrello() {
    	//opzioni relative alla visualizzazione della finestra
        initComponents();
        setResizable(false);
        CatalogoLabel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        CarrelloLabel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        OrdiniLabel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        LogoutLabel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        RimuoviCarrelloBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        EffettuaOrdineBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        setLocationRelativeTo(null);
        
      //mi permette di vedere a video i prodotti del carello in una tabella
        VisualizzaCarrello();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">   
    
    private void VisualizzaCarrello() {
    	
    	Prodotto prodotto = null;
    	DefaultTableModel model = (DefaultTableModel) CarrelloTable.getModel();
    	model.setRowCount(0); // Rimuovi tutte le righe precedenti
    	
    	entity.Carrello carrello = boundaryCliente.VisualizzaCarrello(Login.getUsernameClienteOnline());
    	
    	for(LineaProdotto lineaProdotto : carrello.getProdotti()) {
    		
    		prodotto = boundaryCliente.VisualizzaProdotto(lineaProdotto.getCodiceProdotto());
    		
    	    Object[] rowData = {prodotto.getCodice(), prodotto.getNome(), prodotto.getPrezzo(), lineaProdotto.getQuantita()};
    	    model.addRow(rowData);
    	}
    }
    
    //se clicco su Effettua Ordine, in automatico verrò portato alla schermata Ordini dove visualizzerò
    // il riepilogo degli ordini del cliente online
    private void EffettuaOrdine(){
    	
    	if ( boundaryCliente.EffettuaOrdine(Date.valueOf(LocalDate.now()), Login.getUsernameClienteOnline()) ){
        	JOptionPane.showMessageDialog(this, "Ordine effettuato!");
        	new Ordini().setVisible(true);
        	this.dispose();
    	}

    }
    
    private void RimuoviProdottoCarrello() {
    	
    	int selectedRow = CarrelloTable.getSelectedRow();
        if (selectedRow == -1) {
            // Nessuna riga selezionata, termina senza fare nulla
        	JOptionPane.showMessageDialog(this, "Seleziona il prodotto da eliminare");
            return;
        }
    	boundaryCliente.RimuoviProdottoCarrello(Login.getUsernameClienteOnline(), codiceProdottoSelezionato);
    	VisualizzaCarrello();
    }
    
    private void RimuoviCarrelloBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                   
      
    	RimuoviProdottoCarrello();
    } 
    
    private void EffettuaOrdineBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                  
       
    	EffettuaOrdine();
    } 
    
    private void CarrelloTableMouseClicked(java.awt.event.MouseEvent evt) {                                           
        
    	DefaultTableModel model = (DefaultTableModel) CarrelloTable.getModel();
    	int myRow = CarrelloTable.getSelectedRow();
        codiceProdottoSelezionato = model.getValueAt(myRow, 0).toString(); 
    }
    
    private void CatalogoLabelMouseClicked(java.awt.event.MouseEvent evt) {                                           
        
        new Catalogo().setVisible(true);
        this.dispose();
    }                                          

    private void CarrelloLabelMouseClicked(java.awt.event.MouseEvent evt) {                                           
       
    }                                          

    private void OrdiniLabelMouseClicked(java.awt.event.MouseEvent evt) {                                         
        
        new Ordini().setVisible(true);
        this.dispose();
    }                                        

    private void LogoutLabelMouseClicked(java.awt.event.MouseEvent evt) {                                         
        
        new Login().setVisible(true);
        this.dispose();
    } 
    
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CarrelloTable = new javax.swing.JTable();
        EffettuaOrdineBtn = new javax.swing.JButton();
        RimuoviCarrelloBtn = new javax.swing.JButton();
        CatalogoLabel = new javax.swing.JLabel();
        LogoutLabel = new javax.swing.JLabel();
        OrdiniLabel = new javax.swing.JLabel();
        CarrelloLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Carrello");

        CarrelloTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Codice", "Nome", "Prezzo", "Quantità" 
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CarrelloTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CarrelloTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CarrelloTable);

        EffettuaOrdineBtn.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        EffettuaOrdineBtn.setForeground(new java.awt.Color(51, 51, 255));
        EffettuaOrdineBtn.setText("Effettua Ordine");
        EffettuaOrdineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EffettuaOrdineBtnActionPerformed(evt);
            }
        });

        RimuoviCarrelloBtn.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        RimuoviCarrelloBtn.setForeground(new java.awt.Color(51, 51, 255));
        RimuoviCarrelloBtn.setText("Rimuovi dal carrello");
        RimuoviCarrelloBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RimuoviCarrelloBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(RimuoviCarrelloBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(EffettuaOrdineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EffettuaOrdineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RimuoviCarrelloBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        CatalogoLabel.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        CatalogoLabel.setForeground(new java.awt.Color(51, 51, 255));
        CatalogoLabel.setText("Catalogo");
        CatalogoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CatalogoLabelMouseClicked(evt);
            }
        });

        LogoutLabel.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        LogoutLabel.setForeground(new java.awt.Color(51, 51, 255));
        LogoutLabel.setText("Logout");
        LogoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutLabelMouseClicked(evt);
            }
        });

        OrdiniLabel.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        OrdiniLabel.setForeground(new java.awt.Color(51, 51, 255));
        OrdiniLabel.setText("Ordini");
        OrdiniLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrdiniLabelMouseClicked(evt);
            }
        });

        CarrelloLabel.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        CarrelloLabel.setForeground(new java.awt.Color(51, 51, 255));
        CarrelloLabel.setText("Carrello");
        CarrelloLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CarrelloLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CatalogoLabel)
                    .addComponent(LogoutLabel)
                    .addComponent(OrdiniLabel)
                    .addComponent(CarrelloLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(CatalogoLabel)
                .addGap(18, 18, 18)
                .addComponent(CarrelloLabel)
                .addGap(18, 18, 18)
                .addComponent(OrdiniLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutLabel)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

                                                

                                                 

                                       

                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carrello.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carrello.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carrello.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carrello.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Carrello().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel CarrelloLabel;
    private javax.swing.JTable CarrelloTable;
    private javax.swing.JLabel CatalogoLabel;
    private javax.swing.JButton EffettuaOrdineBtn;
    private javax.swing.JLabel LogoutLabel;
    private javax.swing.JLabel OrdiniLabel;
    private javax.swing.JButton RimuoviCarrelloBtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}

